name: homelab-services

include:
  - ../_common/network.yaml

services:
  redis:
    image: redis:7.0.8
    container_name: redis
    restart: unless-stopped
    networks:
      homelab:
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      resources:
        limits:
          memory: 256M
    command: ["redis-server", "--requirepass 12345678"]
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
