services:
  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 256M
    command: ["redis-server", "--requirepass ${require_pass}", "--appendonly yes", "--appendfsync everysec"]
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"