services:
  jellyfin:
    image: "jellyfin/jellyfin:10.10.7"
    container_name: "jellyfin"
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - /home/tnt/Videos:/media
    restart: 'unless-stopped'
    ports:
      - "8096:8096"
    user: "${UID}:${GID}"
    depends_on:
      - metatube
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]

  metatube:
    image: "ghcr.io/metatube-community/metatube-server:1.3.1"
    container_name: metatube
    restart: 'unless-stopped'
    volumes:
      - ./config/metatube:/config
    environment:
      MT_MOVIE_PROVIDER_PRIORITY_JAVBUS: 1100
    command:
      - "-dsn"
      - "/config/metatube.db"