services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.6
    container_name: "jellyfin"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/tnt/Videos:/media
    restart: 'unless-stopped'
    networks:
      - "jellyfin"
    ports:
      - "8096:8096"
    user: "${UID}:${GID}"
    depends_on:
      - metatube
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]

  metatube:
    image: metatube/metatube-server:1.2.9
    container_name: metatube
    restart: 'unless-stopped'
    networks:
      - "jellyfin"
    ports:
      - "8097:8080"
    volumes:
      - ./metatube/config:/config
    environment:
      MT_MOVIE_PROVIDER_PRIORITY_JAVBUS: 1100
    command:
      - "-dsn"
      - "/config/metatube.db"

networks:
  jellyfin:
    attachable: true
    external: false
    name: "jellyfin"