services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.3
    container_name: "jellyfin"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/tnt/Videos:/media
    restart: 'unless-stopped'
    networks:
      - "jellyfin"
    ports:
      - "8096:8096"
    environment:
      - "NO_PROXY=localhost,127.0.0.1"
      - "HTTPS_PROXY=http://host.docker.internal:12334"
      - "HTTP_PROXY=http://host.docker.internal:12334"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${UID}:${GID}"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]

  jellyfin-vue:
    image: "jellyfin/jellyfin-vue:unstable.2024-11-20.2dc321e"
    container_name: "jellyfin-vue"
    ports:
      - "18080:80"
    networks:
      - "jellyfin"


networks:
  jellyfin:
    attachable: true
    external: false
    name: "jellyfin"