services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.3
    container_name: "jellyfin"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/tnt/Videos:/media
    restart: 'unless-stopped'
    networks:
      - "jellyfin"
    ports:
      - "8096:8096"
    environment:
      - "NO_PROXY=localhost,127.0.0.1"
      - "HTTPS_PROXY=http://host.docker.internal:${PROXY_PORT}"
      - "HTTP_PROXY=http://host.docker.internal:${PROXY_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${UID}:${GID}"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]

networks:
  jellyfin:
    attachable: true
    external: false
    name: "jellyfin"