services:
  dae:
    image: "daeuniverse/dae:20250824"
    volumes:
      - "/sys:/sys"
      - "./config:/etc/dae"
    container_name: "dae"
    networks:
      - "dae"
    restart: unless-stopped
    privileged: true

networks:
  dae:
    name: "dae"