services:
  dae:
    image: "daeuniverse/dae:20250824"
    volumes:
      - "/sys:/sys"
      - "./config:/etc/dae"
    container_name: "dae"
    restart: unless-stopped
    privileged: true
    dns:
      - 119.29.29.29
      - 119.28.28.28