services:
  nacos:
    image: nacos/nacos-server:v3.0.1
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - nacos
      - mysql
    environment:
      - "MODE=standalone" # 单机运行
    env_file:
      - .env
    restart: unless-stopped
networks:
  nacos:
    external: true
  mysql:
    external: true

