version: "3.8"

services:
  clash:
    image: ghcr.io/dreamacro/clash
    restart: always
    volumes:
      - ./config/config.yaml:/root/.config/clash/config.yaml:ro
    dns:
      - 114.114.114.114
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090" # The External Controller (RESTful API)
    network_mode: "bridge"