services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    networks:
      - rabbitmq
    volumes:
      - "./config:/etc/rabbitmq"
      - "./data:/var/lib/rabbitmq"
    deploy:
      resources:
        limits:
          memory: 2048M  # 需要注意，如果限制内存过低，有可能容器启动不起来（ code 0 ）
    restart: unless-stopped


networks:
  rabbitmq:
    name: "rabbitmq"
    external: false
    attachable: true
