services:
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    environment:
      - "MINIO_ROOT_USER=roukaixin"
      - "MINIO_ROOT_PASSWORD=roukaixin"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./data/disk1/minio:/data/disk1/minio
      - ./data/disk2/minio:/data/disk2/minio
      - ./data/disk3/minio:/data/disk3/minio
      - ./data/disk4/minio:/data/disk4/minio
    command:
      - "server"
      - "http://minio{1...4}:9000/data/disk{1...4}/minio"
      - "--console-address"
      - ":9090"
    extra_hosts:
      - "minio1:10.1.1.1"
      - "minio2:10.1.1.2"
      - "minio3:10.1.1.3"
      - "minio4:10.1.1.4"
    network_mode: "host"