services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "elastic"
    volumes:
      - "./data:/usr/share/elasticsearch/data"
      - "./plugins:/usr/share/elasticsearch/plugins"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  elastic:
    external: true