services:
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    environment:
      - USER=${USER}
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=127.0.0.1
      - GITEA__server__SSH_DOMAIN=127.0.0.1:10022
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://127.0.0.1:10880/
      - GITEA__server__SSH_PORT=22
      - GITEA__server__BUILTIN_SSH_SERVER_USER=git
      - GITEA__server__SSH_CREATE_AUTHORIZED_KEYS_FILE=true
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__server__SSH_EXPOSE_ANONYMOUS=true
      - GITEA__server__LANDING_PAGE=explore
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=12345678
      - GITEA__database__LOG_SQL=false
      - GITEA__database__SSL_MODE=false
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__PASSWORD_HASH_ALGO=bcrypt
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - GITEA__service__REGISTER_EMAIL_CONFIRM=false
      - GITEA__service__ENABLE_NOTIFY_MAIL=false
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=false
      - GITEA__service__ENABLE_CAPTCHA=true
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA__service__DEFAULT_ENABLE_TIMETRACKING=true
      - GITEA__service__REQUIRE_CAPTCHA_FOR_LOGIN=true
      - GITEA__service__CAPTCHA_TYPE=image
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__storage__STORAGE_TYPE=minio
      - GITEA__storage__MINIO_ENDPOINT=minio:9000
      - GITEA__storage__MINIO_BUCKET=gitea
      - GITEA__storage__MINIO_ACCESS_KEY_ID=minio
      - GITEA__storage__MINIO_SECRET_ACCESS_KEY=12345678
      - GITEA__repository.upload__FILE_MAX_SIZE=100
      - GITEA__i18n__LANGS=en-US,zh-CN
      - GITEA__i18n__NAMES=English,简体中文
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME=false
      - GITEA__other__SHOW_FOOTER_POWERED_BY=false
      - GITEA__api__ENABLE_SWAGGER=false
      - GITEA__time__DEFAULT_UI_LOCATION=Asia/Shanghai
      - GITEA__ui__SHOW_USER_EMAIL=false
      - GITEA__cron.resync_all_sshkeys__ENABLED=true
      - GITEA__cron.resync_all_sshkeys__RUN_AT_START=true
      - GITEA__cron.update_checker__ENABLED=false
      - GITEA__repository.pull-request__DEFAULT_MERGE_STYLE=merge
      - GITEA__repository.signing__DEFAULT_TRUST_MODEL=committer
      - GITEA__mailer__ENABLED=false
    ports:
      - "10880:3000"
      - "10022:22"
    networks:
      - gitea
      - mysql
      - minio
    volumes:
      - ./data/gitea:/data
      - ./.env:/.env:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 1s
      retries: 1
    command: /bin/sh -c \
      "nohup /bin/s6-svscan /etc/s6 > ~/gitea.log 2>&1 & \
      while true; do if grep -q \"Starting new Web server\" ~/gitea.log; then echo $(su  tnt -c '/usr/local/bin/gitea actions generate-runner-token' | tail -n 1) > ~/runner_registration_token; break; else sleep 1; fi done && \
      cat ~/runner_registration_token && \
      echo GITEA_RUNNER_REGISTRATION_TOKEN= > /.env && \
      sed \"s/GITEA_RUNNER_REGISTRATION_TOKEN=.*/GITEA_RUNNER_REGISTRATION_TOKEN=$(cat ~/runner_registration_token)/\" /.env > ~/.env && \
      cat ~/.env > /.env && \
      rm ~/.env && \
      rm ~/runner_registration_token && \
      tail -f ~/gitea.log"

  runner:
    image: gitea/act_runner:0.2.10
    container_name: runner
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea:3000/
    volumes:
      - ./config/config.yaml:/config.yaml:ro
      - ./data/runner:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/.env:ro
    networks:
      - gitea
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      gitea:
        condition: service_healthy
    entrypoint: /bin/sh -c "cat /.env && export $(cat /.env) && /sbin/tini -- /opt/act/run.sh"

networks:
  gitea:
    name: gitea
    external: false
  mysql:
    external: true
  minio:
    external: true