services:
  trilium:
    image: "triliumnext/trilium:v0.99.1"
    ports:
      - "9080:8080"
    volumes:
      - "./data:/home/node/trilium-data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}