services:
    aList:
        image: xhofe/alist:v3.40.0-ffmpeg
        container_name: alist
        environment:
            - "PUID=${PUID}"
            - "PGID=${PGID}"
            - "UMASK=${UMASK}"
            - "TZ=Asia/Shanghai"
        volumes:
            - "./data:/opt/alist/data"
        ports:
            - "5244:5244"
        restart: unless-stopped
        networks:
            - alist
            - aria2
        dns: 8.8.8.8

networks:
    alist:
        external: false
        name: alist
    aria2:
        name: aria2
        external: true