services:
    aList:
        image: xhofe/alist-aria2
        container_name: alist
        environment:
            - "PUID=1000"
            - "PGID=1000"
            - "UMASK=022"
        volumes:
            - "./data:/opt/alist/data"
        ports:
            - "5244:5244"