version: '3.8'
services:
    aList:
        restart: always
        volumes:
            - ./data:/opt/alist/data
        ports:
            - '5244:5244'
        container_name: alist
        image: xhofe/alist-aria2
