services:
  gogs:
    image: gogs/gogs:0.12.10
    volumes:
      - "./data:/data"
    ports:
      - "10022:22"
      - "10880:3000"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    external: true