services:
  kafka:
    image: apache/kafka-native:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka
    restart: unless-stopped

networks:
  kafka:
    external: false
    name: kafka