services:
  redroid:
    image: redroid/redroid:11.0.0-240527
    container_name: "redroid"
    volumes:
      - "./data:/data"
    ports:
      - "5555:5555"
    privileged: true
    command:
      - "androidboot.use_memfd=1"
      # 啟用GPU硬體加速
      - "androidboot.redroid_gpu_mode=auto"
      # 設定libndk相關
      - "ro.product.cpu.abilist0=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi"
      - "ro.product.cpu.abilist64=x86_64,arm64-v8a"
      - "ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi"
      - "ro.dalvik.vm.isa.arm=x86"
      - "ro.dalvik.vm.isa.arm64=x86_64"
      - "ro.enable.native.bridge.exec=1"
      - "ro.dalvik.vm.native.bridge=libndk_translation.so"
      - "ro.ndk_translation.version=0.2.2"
    networks:
      - "redroid"
    stdin_open: true
networks:
  redroid:
    external: false
    name: "redroid"