services:
  v2raya:
    container_name: v2raya
    image: mzz2017/v2raya:v2.2.5.7
    network_mode: host
    volumes:
      - ./data:/etc/v2raya
    environment:
      - "V2RAYA_NFTABLES_SUPPORT=on"
    privileged: true
    restart: unless-stopped