services:
  dm:
    image: dm8_single:dm8_20230808_rev197096_x86_rh6_64
    privileged: true
    restart: always
    volumes:
      - "./data:/opt/dmdbms/data"
    ports:
      - "127.0.0.1:5236:5236"
    networks:
      - dm
    environment:
      - "PAGE_SIZE=32"
      - "LD_LIBRARY_PATH=/opt/dmdbms/bin"
      - "INSTANCE_NAME=dm8"
      - "CASE_SENSITIVE=0"
      - "UNICODE_FLAG=1"
      - "EXTENT_SIZE=32"
      - "BLANK_PAD_MODE=1"
      - "LOG_SIZE=1024"
      - "LENGTH_IN_CHAR=1"
      - "SYSDBA_PWD=12345678"

networks:
  dm:
    external: true