services:
  qinglong:
    image: whyour/qinglong:2.18.2
    container_name: "qinglong"
    volumes:
      - ./data:/ql/data
    ports:
      - "5700:5700"
    restart: unless-stopped
    networks:
      - "qinglong"
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  qinglong:
    name: "qinglong"
    external: false