services:
  web:
    image: whyour/qinglong:2.17.6
    container_name: qinglong
    volumes:
      - ./data:/ql/data
    ports:
      - "5700:5700"
    restart: unless-stopped
    networks:
      - qinglong
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  qinglong:
    name: qinglong
    external: false