services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.9.3
    container_name: sing-box
    restart: unless-stopped
    volumes:
      - "./data:/etc/sing-box/"
    command: -D /var/lib/sing-box -C /etc/sing-box/ run