version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=rabbitmq"
    env_file:
      - ./.env
    networks:
      - rabbitmq
    volumes:
      - ./config:/etc/rabbitmq
      - ./data:/var/lib/rabbitmq
      - ./logs:/var/log/rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always


networks:
  rabbitmq:
    external: true