services:
  moviepilot:
    image: jxxghp/moviepilot-v2:2.3.4
    stdin_open: true
    tty: true
    container_name: moviepilot-v2
    hostname: moviepilot-v2

    ports:
      - '3000:3000'
      - '3001:3001'

    volumes:
      - './data/media:/media'
      - './config:/config'
      - './core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

    environment:
      - 'NGINX_PORT=3000'
      - 'PORT=3001'
      - 'PUID=1000'
      - 'PGID=1000'
      - 'UMASK=000'
      - 'TZ=Asia/Shanghai'
      - 'SUPERUSER=admin'

    restart: unless-stopped