services:
  moviepilot:
    image: "ghcr.io/jxxghp/moviepilot:2.8.1-1"
    stdin_open: true
    tty: true
    container_name: moviepilot
    hostname: moviepilot
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - './data/media:/media'
      - './config:/config'
      - './core:/moviepilot/.cache/ms-playwright'
    environment:
      - 'NGINX_PORT=3000'
      - 'PORT=3001'
      - 'PUID=1000'
      - 'PGID=1000'
      - 'UMASK=000'
      - 'TZ=Asia/Shanghai'
      - 'SUPERUSER=admin'
    restart: unless-stopped
    networks:
      - "moviepilot"
    logging:
      driver: local
      options:
        max-size: 2m

networks:
  moviepilot:
    name: "moviepilot"
    external: false
