name: homelab-services

include:
  - ../_common/network.yaml

services:
  sing-box:
    image: sing-box:${SING_BOX_VERSION}-${REDIRECT_PKG_HANDLER_VERSION}
    build:
      dockerfile: Dockerfile
      args:
        REDIRECT_PKG_HANDLER_VERSION: ${REDIRECT_PKG_HANDLER_VERSION}
        SING_BOX_VERSION: ${SING_BOX_VERSION}
    container_name: "sing-box"
    ports:
      - "9090:9090"
      - "7890:7890"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.lo.accept_local=1
    cap_add:
      - NET_ADMIN
      - BPF
      - PERFMON
    privileged: true
    environment:
      SERVER_RUN_WORK_DIR: ${SERVER_RUN_WORK_DIR}
    volumes:
      - "${LANDSCAPE_CONFIG_DIR}/unix_link/:/ld_unix_link/:ro"
      - "./data:${SERVER_RUN_WORK_DIR}"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
    networks:
      homelab:
        ipv4_address: 172.28.200.100