services:
  osx:
    image: sickcodes/docker-osx:ventura
    container_name: osx
    ports:
      - "50922:10022"
    devices:
      - "/dev/kvm"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
      - GENERATE_UNIQUE=true
      - CPUID_FLAGS='kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on'
      - MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist'
    restart: unless-stopped