apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:9.2.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
          protocol: TCP
          hostPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: TZ
          value: "Asia/Shanghai"
        - name: MYSQL_INIT_SQL
          value: "SET @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE'"
      resources:
        requests:
          memory: 128Mi
        limits:
          memory: 256Mi
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      args:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_general_ci"
  restartPolicy: Always
  volumes:
    - name: mysql-data
      hostPath:
        path: ./data
        type: "DirectoryOrCreate"
