services:
    openlist:
        image: "openlistteam/openlist:v4.0.5-ffmpeg"
        container_name: "openlist"
        environment:
            - "PUID=${PUID}"
            - "PGID=${PGID}"
            - "UMASK=${UMASK}"
            - "TZ=Asia/Shanghai"
        volumes:
            - "./data:/opt/alist/data"
        ports:
            - "5244:5244"
        restart: unless-stopped
        networks:
            - openlist
            - aria2
        dns: 8.8.8.8

networks:
    openlist:
        external: false
        name: openlist
        attachable: true
    aria2:
        name: aria2
        external: true