services:
  gecoos-ac:
    image: "adxing/gecoos-ac:v2.2"
    container_name: "gecoos-ac"
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "60650:60650"
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "./data:/data"
    environment:
      mp: ${WEB_PORT}
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"