services:
  gecoos-ac:
    image: "tearsful/gecoosac:V2"
    container_name: "gecoos-ac"
    restart: unless-stopped
    ports:
      - "60650:60650"
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "./data:/data"
    environment:
      webport: ${WEB_PORT}
      UID: 0
      GID: 0
      GIDLIST: 0
      passwd: ${PASSWORD}
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"