name: gitea
services:
  gitea:
    image: gitea/gitea:28.0.0
    container_name: ${GITEA__CONTAINER_NAME}
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA_CUSTOM: /custom
      GITEA__server__DOMAIN: ${DOMAIN}
      GITEA__server__SSH_DOMAIN: ${DOMAIN}
      GITEA__server__HTTP_PORT: ${GITEA__HTTP_PORT}
      GITEA__server__SSH_PORT: ${SSH_PORT}
      GITEA__server__SSH_LISTEN_PORT: ${SSH_LISTEN_PORT}
      GITEA__server__BUILTIN_SSH_SERVER_USER: git
      GITEA__server__SSH_CREATE_AUTHORIZED_KEYS_FILE: true
      GITEA__server__LFS_START_SERVER: true
      GITEA__server__LANDING_PAGE: explore
      GITEA__server__OFFLINE_MODE: true
      GITEA__database__DB_TYPE: ${DB_TYPE}
      GITEA__database__LOG_SQL: false
      GITEA__database__SSL_MODE: false
      GITEA__security__INSTALL_LOCK: true
      GITEA__security__PASSWORD_HASH_ALGO: bcrypt
      GITEA__service__DISABLE_REGISTRATION: true
      GITEA__service__REQUIRE_SIGNIN_VIEW: false
      GITEA__service__REGISTER_EMAIL_CONFIRM: false
      GITEA__service__ENABLE_NOTIFY_MAIL: false
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: false
      GITEA__service__ENABLE_CAPTCHA: true
      GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE: false
      GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: true
      GITEA__service__DEFAULT_ENABLE_TIMETRACKING: true
      GITEA__service__REQUIRE_CAPTCHA_FOR_LOGIN: true
      GITEA__service__CAPTCHA_TYPE: image
      GITEA__service.explore__DISABLE_USERS_PAGE: true
      GITEA__openid__ENABLE_OPENID_SIGNIN: false
      GITEA__openid__ENABLE_OPENID_SIGNUP: false
      GITEA__storage__STORAGE_TYPE: minio
      GITEA__storage__MINIO_ENDPOINT: ${STORAGE__CONTAINER_NAME}${STORAGE__RUSTFS_ADDRESS}
      GITEA__storage__MINIO_BUCKET: ${MINIO_BUCKET}
      GITEA__storage__MINIO_ACCESS_KEY_ID: ${STORAGE__RUSTFS_ACCESS_KEY}
      GITEA__storage__MINIO_SECRET_ACCESS_KEY: ${STORAGE__RUSTFS_SECRET_KEY}
      GITEA__repository__ROOT: "repo"
      GITEA__repository.upload__FILE_MAX_SIZE: ${UPLOAD_FILE_MAX_SIZE}
      GITEA__i18n__LANGS: en-US,zh-CN
      GITEA__i18n__NAMES: English,简体中文
      GITEA__other__SHOW_FOOTER_VERSION: false
      GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME: false
      GITEA__other__SHOW_FOOTER_POWERED_BY: false
      GITEA__api__ENABLE_SWAGGER: false
      GITEA__time__DEFAULT_UI_LOCATION: Asia/Shanghai
      GITEA__ui__SHOW_USER_EMAIL: false
      GITEA__cron.resync_all_sshkeys__ENABLED: true
      GITEA__cron.resync_all_sshkeys__RUN_AT_START: true
      GITEA__cron.update_checker__ENABLED: false
      GITEA__repository.pull-request__DEFAULT_MERGE_STYLE: merge
      GITEA__repository.signing__DEFAULT_TRUST_MODEL: committer
      GITEA__mailer__ENABLED: false
      GITEA__session__PROVIDER: db
      GITEA__queue__TYPE: level
      GITEA_RUNNER_REGISTRATION_TOKEN: ${RUNNER_REGISTRATION_TOKEN}
    ports:
      - "${GITEA__HTTP_PORT}:${GITEA__HTTP_PORT}"
      - "${SSH_PORT}:22"
    volumes:
      - ./data/gitea/work:/data/gitea
      - ./data/gitea/custom:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:${GITEA__HTTP_PORT}" ]
      interval: 5s
      timeout: 2s
      start_period: 5s
      retries: 3
    depends_on:
      rustfs:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

  act_runner:
    image: gitea/runner:4.0.1-dind
    container_name: ${RUNNER__CONTAINER_NAME}
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: http://${GITEA__CONTAINER_NAME}:${GITEA__HTTP_PORT}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${RUNNER_NAME}
    volumes:
      - ./config/config.yaml:/config.yaml:ro
      - ./data/runner:/data:rw
    depends_on:
      gitea:
        condition: service_healthy
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        limits:
          memory: 2048M
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

  rustfs:
    image: ghcr.io/rustfs/rustfs:1.0.1
    container_name: ${STORAGE__CONTAINER_NAME}
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: ${STORAGE__RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${STORAGE__RUSTFS_SECRET_KEY}
      RUSTFS_ADDRESS: ${STORAGE__RUSTFS_ADDRESS}
      RUSTFS_CONSOLE_ENABLE: "false"
      RUSTFS_OBS_LOGGER_LEVEL: info
      RUSTFS_VOLUMES: /data/rustfs{0...3}
      RUSTFS_UNSAFE_BYPASS_DISK_CHECK: "true"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
    healthcheck:
      test: [ "CMD", "sh", "-ec", "curl http://127.0.0.1${STORAGE__RUSTFS_ADDRESS}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - "rustfs:/data"

volumes:
  rustfs:
    name: rustfs
    external: true