services:
  clash:
    image: ghcr.io/dreamacro/clash
    restart: unless-stopped
    volumes:
      - "./config/config.yaml:/root/.config/clash/config.yaml:ro"
    dns:
      - "114.114.114.114"
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090" # The External Controller (RESTful API)
    networks:
      - "clash"

  clash-dashboard:
    image: centralx/clash-dashboard
    ports:
      - "8080:80"
    networks:
      - "clash"
    restart: unless-stopped

networks:
  clash:
    external: true