apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:7.0.8
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
          protocol: TCP
          hostPort: 6379
      volumeMounts:
        - mountPath: /data
          name: data
      command: [ "redis-server" ]
      args: [ "--requirepass 12345678" ]
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
  volumes:
    - name: data
      hostPath:
        path: ./data
        type: "DirectoryOrCreate"
  restartPolicy: Always
