services:
  rustfs:
    image: ghcr.io/rustfs/rustfs:1.0.1
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: 12345678
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_OBS_LOGGER_LEVEL: info
      RUSTFS_VOLUMES: /data/rustfs{0...3}
      RUSTFS_UNSAFE_BYPASS_DISK_CHECK: "true"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
    volumes:
      - "rustfs:/data"

volumes:
  rustfs:
    name: rustfs
    external: true