services:
  server:
    image: gitea/gitea:1.22.0-rootless
    container_name: gitea
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql:3306
      - DB_NAME=gitea
      - DB_USER=root
      - DB_PASSWD=12345678
      - USER=${USER}
      - GITEA__server__SSH_USER=
    restart: always
    networks:
      - gitea
      - mysql
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10880:3000"
      - "10022:2222"
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  gitea:
    external: false
  mysql:
    external: true