services:
  gitea:
    image: gitea/gitea:1.22.0-rootless
    container_name: gitea
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql:3306
      - DB_NAME=gitea
      - DB_USER=root
      - DB_PASSWD=12345678
      - USER=${USER}
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__BUILTIN_SSH_SERVER_USER=git
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__service__ENABLE_CAPTCHA=true
      - GITEA__service__REQUIRE_CAPTCHA_FOR_LOGIN=true
      - GITEA__service__CAPTCHA_TYPE=image
      - GITEA__storage__STORAGE_TYPE=minio
      - GITEA__storage__MINIO_ENDPOINT=minio:9000
      - GITEA__storage__MINIO_BUCKET=gitea
      - GITEA__storage__MINIO_ACCESS_KEY_ID=minio
      - GITEA__storage__MINIO_SECRET_ACCESS_KEY=12345678
      - GITEA__repository.upload__FILE_MAX_SIZE=100
      - GITEA__i18n__LANGS=en-US,zh-CN
      - GITEA__i18n__NAMES=English,简体中文
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME=false
      - GITEA__other__SHOW_FOOTER_POWERED_BY=false
      - GITEA__api__ENABLE_SWAGGER=false
      - GITEA__server__LANDING_PAGE=explore
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DOMAIN=127.0.0.1
      - GITEA__server__ROOT_URL=http://127.0.0.1:10880/
      - GITEA__server__SSH_PORT=10022
      - GITEA__server__SSH_LISTEN_PORT=2222
      - GITEA__time__DEFAULT_UI_LOCATION=Asia/Shanghai
      - GITEA__repository__USE_COMPAT_SSH_URI=true
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=12345678
    restart: always
    user: 1000:1000
    networks:
      - gitea
      - mysql
      - minio
    volumes:
      - ./data/gitea:/var/lib/gitea
      - ./config/gitea:/etc/gitea
      - ./.env:/env/.env:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10880:3000"
      - "10022:2222"
    command: /bin/sh -c \
      "nohup /usr/local/bin/gitea web -c /etc/gitea/app.ini > ~/gitea.log 2>&1 & \
      sleep 5 && \
      echo $(/usr/local/bin/gitea --config /etc/gitea/app.ini actions generate-runner-token | tail -n 1) > start && \
      cat start && \
      echo GITEA_RUNNER_REGISTRATION_TOKEN= > /env/.env && \
      sed \"s/GITEA_RUNNER_REGISTRATION_TOKEN=.*/GITEA_RUNNER_REGISTRATION_TOKEN=$(cat start)/\" /env/.env > /var/lib/gitea/.env && \
      rm /var/lib/gitea/start && \
      cat /var/lib/gitea/.env > /env/.env && \
      rm /var/lib/gitea/.env && \
      tail -f ~/gitea.log"

  runner:
    image: gitea/act_runner:0.2.10
    container_name: runner
    env_file:
      - ./.env
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea:3000/
    volumes:
      - ./config/runner/config.yaml:/config.yaml:ro
      - ./data/runner:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - gitea


networks:
  gitea:
    name: gitea
    external: false
  mysql:
    external: true
  minio:
    external: true