services:
  memos:
    image: neosmemo/memos:0.22.3
    container_name: memos
    volumes:
      - "./data/:${MEMOS_DATA}"
    ports:
      - "5230:${MEMOS_PORT}"
    restart: unless-stopped
    networks:
      - memos
      - mysql
networks:
  memos:
    external: false
    name: memos
  mysql:
    external: true