services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    networks:
      - "mysql"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      TZ: "Asia/Shanghai"
    # 不知道什么原因，使用 5.7.41 的镜像加入资源限制启动不起来
    deploy:
      resources:
        limits:
          memory: 512M
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    restart: unless-stopped

networks:
  mysql:
    name: "mysql"
    attachable: true
    external: false