include:
  - ../commons/docker-compose-application-include.yaml

services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=application"
      - "--api.dashboard=true"
      - "--api.disabledashboardad=true"
      - "--api.insecure=false"
      - "--log.level=INFO"
      - "--accesslog=true"
      # 自动颁发证书
      - "--certificatesresolvers.le.acme.email=your-email@gmain.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.${domain}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$9qxYYb1H$$FR/TdcSGc7Z/7rldthJ5g1"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
      # 解析证书
      - "traefik.http.routers.dashboard.tls.certresolver=le"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
