services:
  mtranserver:
    image: ghcr.io/xxnuo/mtranserver:4.0.33
    container_name: mtranserver
    restart: unless-stopped
    ports:
      - "${MT_PORT}:${MT_PORT}"
    environment:
      MT_HOST: 0.0.0.0
      MT_PORT: "${MT_PORT}"
      MT_OFFLINE: false
      MT_API_TOKEN: ${MT_API_TOKEN}
      MT_LOG_LEVEL: debug
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"