name: homelab-services

services:
  mtranserver:
    image: xxnuo/mtranserver
    container_name: mtranserver
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      API_TOKEN: ${API_TOKEN}
    volumes:
      - "./models:/app/models"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"