services:
  hoppscotch-db:
    container_name: hoppscotch-db
    image: postgres:17.4-alpine
    user: "${UID}:${GID}"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: hoppscotch
      LANG: zh_CN.UTF-8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - "./data:/var/lib/postgresql/data"
    restart: unless-stopped

  hoppscotch-aio:
    container_name: hoppscotch-aio
    image: hoppscotch/hoppscotch:2025.2.1
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@hoppscotch-db:5432/hoppscotch
      ENABLE_SUBPATH_BASED_ACCESS: true
      JWT_SECRET: 12345678
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"
      - "3080:80"
    restart: unless-stopped
#    command: ["sh", "-c", "pnpm exec prisma migrate deploy && node /usr/src/app/aio_run.mjs"]